version: "3.9"
services:
  mongo:
    image: mongo:5.0.10
    container_name: mongo
    # Provide mongo config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    # Set health checks to wait until mongo has started
    #volumes:
    # -  ./data-vol:/data/db 
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
    # Maps tcp port to host
    #ports:
    #  - 27017:27017
    
  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt
    ports:
      - 1884:1884
      
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    ports:
        - 8081:8081
    depends_on:
        mongo:
            condition: service_healthy
        mqtt:
            condition: service_healthy
        aas-registry:
            condition: service_healthy
        sm-registry:
            condition: service_healthy
            
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - 8082:8080
    depends_on:
      mongo:
        condition: service_healthy
    
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - 8083:8083
    depends_on:
      mongo:
        condition: service_healthy

  databridge:
      container_name: databridge
      ports:
          - 8085:8085
      image: eclipsebasyx/databridge:1.0.0-SNAPSHOT
      depends_on:
        aas-env:
          condition: service_healthy


# environment:
#       AAS_REGISTRY_PATH: "http://localhost:8082"
#       SUBMODEL_REGISTRY_PATH: "http://localhost:8083"
#       AAS_DISCOVERY_PATH: "http://localhost:8084"
#       AAS_REPO_PATH: "http://localhost:8081/shells"
#       SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"
#       CD_REPO_PATH: "http://localhost:8081/concept-descriptions"
