name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Start environment
      run: docker compose --project-directory ./ci up -d --wait
    - name: Stop environment
      if: always()
      run: docker  compose --project-directory ./ci down
